### ISSUE TITLE
Release 0.1.7 not working

### ISSUE THREAD

**Issue by mtilstra** [jonkristian/casatunes#12]
Everything was working on release 0.1.6.  After updating to release 0.1.7, on the Integrations page, it shows a red exclamation and says "Failed to set up"

From the logs (full log attached):
  File "/config/custom_components/casatunes/media_player.py", line 30, in <module>
    from .const import ATTR_KEYWORD, DOMAIN, SERVICE_SEARCH
ImportError: cannot import name 'ATTR_KEYWORD' from 'custom_components.casatunes.const' (/config/custom_components/casatunes/const.py)

[casatunes 0.1.7 log.txt](https://github.com/user-attachments/files/18924592/casatunes.0.1.7.log.txt)

Reverting back to release 0.1.6 works again, but gives warnings about deprecated constants that will be removed in HA Core 2025.10

**Comment by mtilstra** [comment]
I am not certain, but it appears the changes made in pull request #10 were changes that should have been applied to the 0.1.6 release 8824ee0, and not to the latest code that was added in master after the 0.1.6 release.

**Comment by alphasixtyfive** [comment]
Please try my fork. I've updated a few files manually and reverted some changes that broke the integration. 

https://github.com/alphasixtyfive/casatunes

**Comment by mtilstra** [comment]
@alphasixtyfive I installed your fork and it appears to be working correctly.

**Comment by alphasixtyfive** [comment]
@mtilstra Glad to hear it.

**Comment by scyto** [comment]
@alphasixtyfive 

not sure if you are still maintaining your own version, did you notice this?

```
Logger: homeassistant.components.ssdp
Source: helpers/deprecation.py:257
integration: Simple Service Discovery Protocol (SSDP) (documentation, issues)
First occurred: 7:15:18 PM (4 occurrences)
Last logged: 7:15:18 PM

The deprecated constant ATTR_UPNP_FRIENDLY_NAME was used from casatunes. It will be removed in HA Core 2026.2. Use homeassistant.helpers.service_info.ssdp.ATTR_UPNP_FRIENDLY_NAME instead, please report it to the author of the 'casatunes' custom integration
The deprecated constant ATTR_UPNP_SERIAL was used from casatunes. It will be removed in HA Core 2026.2. Use homeassistant.helpers.service_info.ssdp.ATTR_UPNP_SERIAL instead, please report it to the author of the 'casatunes' custom integration
```
